language: csharp
os: 
  - linux


sudo: required
mono: none
dist: xenial
dotnet: 3.0.100

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
     - libunwind8

  
git:
  depth: false
before_script:
- sudo apt-get install dotnet-sdk-2.2
- cd src

script:
- dotnet restore Build.csproj
- dotnet flubu rebuild.linux -s=BuildScript/BuildScript.cs
